apiVersion: v1
kind: Service
metadata:
  labels:
    app: starwars
  name: sw-service
spec:
  ports:
  - port: 6969
    protocol: TCP
    targetPort: 6969
  selector:
    app: starwars
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: starwars
  name: starwars
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starwars
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: starwars
    spec:
      containers:
      - image: starwars:1.0
        name: starwars
